#CI/MANUAL TRIGGER
name: Build

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build_DotNet_OS-VSVersion:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019 ]
        vs-version: [ '16.1']
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Nuget Restore
      run: nuget restore GmailAPIHelper.sln -Verbosity quiet

    - name: Setup-MSBuild VS-Version (${{ matrix.vs-version }})
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: ${{ matrix.vs-version }}
      
    - name: Find And Replace Values (App Config)
      uses: abhinavminhas/replace-tokens@v1.0
      with:
        files: '${{ github.workspace }}\GmailAPIHelper.NET.Tests\App.config'
        replacements: '__GMAILID__=${{ secrets.GMAIL_ID }}'

    - name: Build
      id: build
      run: |
        msbuild GmailAPIHelper.sln /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

    - name: Find And Replace Values (OAuth)
      uses: abhinavminhas/replace-tokens@v1.0
      with:
        files: '${{ github.workspace }}\GmailAPIHelper.NET.Tests\bin\Release\token.json\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user'
        replacements: '__ACCESSTOKEN__=${{ secrets.ACCESS_TOKEN }}'
    
    - name: Find And Replace Values (Client Secret)
      uses: abhinavminhas/replace-tokens@v1.0
      with:
        files: '${{ github.workspace }}\GmailAPIHelper.NET.Tests\bin\Release\credentials.json'
        replacements: '__CLIENTSECRET__=${{ secrets.CLIENT_SECRET }}'
        
    - name: Setup-VSTest
      uses: darenm/Setup-VSTest@v1.2
      
    - name: Test
      run: vstest.console.exe ${{ github.workspace }}\GmailAPIHelper.NET.Tests\bin\Release\GmailAPIHelper.NET.Tests.dll /TestCaseFilter:"TestCategory=GMAIL-TESTS-DOTNETFRAMEWORK"
    
  
  Build_DotNetCore_OS-Version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-20.04, macOS-11 ]
        dotnet-version: [ '3.1.x', '6.0.x' ]
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Dotnet Version (${{ matrix.dotnet-version }})
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Find And Replace Values (App Config)
      uses: abhinavminhas/replace-tokens@v1.0
      with:
        files: '${{ github.workspace }}/GmailAPIHelper.CORE.Tests/App.config'
        replacements: '__GMAILID__=${{ secrets.GMAIL_ID }}'
        
    - name: Build
      run: dotnet build GmailAPIHelper.CORE.Tests/GmailAPIHelper.CORE.Tests.csproj --configuration Release

    - name: Find And Replace Values (OAuth)
      if: ${{ matrix.dotnet-version == 'N/A' }}
      uses: abhinavminhas/replace-tokens@v1.0
      with:
        files: '${{ github.workspace }}/GmailAPIHelper.CORE.Tests/bin/Release/netcoreapp3.1/token.json/Google.Apis.Auth.OAuth2.Responses.TokenResponse-user'
        replacements: '__ACCESSTOKEN__=${{ secrets.ACCESS_TOKEN }}'

    - name: Find And Replace Values (Client Secret)
      if: ${{ matrix.dotnet-version == 'N/A' }}
      uses: abhinavminhas/replace-tokens@v1.0
      with:
        files: '${{ github.workspace }}/GmailAPIHelper.CORE.Tests/bin/Release/netcoreapp3.1/credentials.json'
        replacements: '__CLIENTSECRET__=${{ secrets.CLIENT_SECRET }}'
    
    - name: Test
      if: ${{ matrix.dotnet-version == 'N/A' }}
      run: dotnet test --no-build --verbosity normal --configuration Release --filter TestCategory=GMAIL-TESTS-DOTNETCORE

  Code-Coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-20.04, macOS-11 ]
        dotnet-version: [ '3.1.x' ]
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Dotnet Version (${{ matrix.dotnet-version }})
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Find And Replace Values (App Config)
      uses: abhinavminhas/replace-tokens@v1.0
      with:
        files: '${{ github.workspace }}/GmailAPIHelper.CORE.Tests/App.config'
        replacements: '__GMAILID__=${{ secrets.GMAIL_ID }}'

    - name: Build
      run: dotnet build GmailAPIHelper.CORE.Tests/GmailAPIHelper.CORE.Tests.csproj --configuration Release

    - name: Find And Replace Values (OAuth)
      if: ${{ matrix.dotnet-version == '3.1.x' }}
      uses: abhinavminhas/replace-tokens@v1.0
      with:
        files: '${{ github.workspace }}/GmailAPIHelper.CORE.Tests/bin/Release/netcoreapp3.1/token.json/Google.Apis.Auth.OAuth2.Responses.TokenResponse-user'
        replacements: '__ACCESSTOKEN__=${{ secrets.ACCESS_TOKEN }}'

    - name: Find And Replace Values (Client Secret)
      if: ${{ matrix.dotnet-version == '3.1.x' }}
      uses: abhinavminhas/replace-tokens@v1.0
      with:
        files: '${{ github.workspace }}/GmailAPIHelper.CORE.Tests/bin/Release/netcoreapp3.1/credentials.json'
        replacements: '__CLIENTSECRET__=${{ secrets.CLIENT_SECRET }}'
        
    - name: Test
      if: ${{ matrix.dotnet-version == '3.1.x' }}
      run: dotnet test --no-build --verbosity normal --configuration Release --filter TestCategory=GMAIL-TESTS-DOTNETCORE /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
    
    - name: Upload Coverage To Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
