name: Code Quality (SonarCloud)
on:
  workflow_dispatch:

jobs:
  build:
    name: Code Quality (SonarCloud)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        dotnet-version: [ '3.1.x' ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dotnet Version (${{ matrix.dotnet-version }})
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build
        run: dotnet build GmailAPIHelper.CORE.Tests/GmailAPIHelper.CORE.Tests.csproj --configuration Release
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_1 }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKe=${{ secrets.SONAR_PROJECT_KEY }}