#CI/SCHEDULE/MANUAL TRIGGER
name: Build

on: 
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Nuget Restore
      run: nuget restore GmailAPIHelper.sln -Verbosity quiet

    - name: Setup-MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build
      id: build
      run: |
        msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: trxer-console
        path: ${{ github.workspace }}
        retention-days: 90
