#CI/SCHEDULE/MANUAL TRIGGER
name: Build

on: 
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build-DOTNETFRAMEWORK:
    runs-on: windows-latest
        
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Nuget Restore
      run: nuget restore GmailAPIHelper.sln -Verbosity quiet

    - name: Setup-MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Build
      id: build
      run: |
        msbuild GmailAPIHelper.sln /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
    
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
      
    - name: Run Tests
      run: vstest.console.exe ${{ github.workspace }}\GmailAPIHelper.NET.Tests\bin\Release\GmailAPIHelper.NET.Tests.dll
  
  build-DOTNETCORE:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macOS-latest ]
        dotnet: [ '2.1.x', '3.1.x', '5.0.x' ]
        
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 
    - name: Dotnet ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: Build
    - run: dotnet build GmailAPIHelper.CORE.Tests/GmailAPIHelper.CORE.Tests.csproj --configuration Release
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
