#CI/MANUAL TRIGGER
name: Build

on: 
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  DotNet_OS-VSVersion:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        vs-version: [ '15.9']
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Nuget Restore
      run: nuget restore GmailAPIHelper.sln -Verbosity quiet

    - name: Setup-MSBuild VS-Version (${{ matrix.vs-version }})
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: ${{ matrix.vs-version }}
      
    - name: Build
      id: build
      run: |
        msbuild GmailAPIHelper.sln /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
    
    - name: Find And Replace Values
      uses: datamonsters/replace-action@v2
      with:
        files: '${{ github.workspace }}\GmailAPIHelper.NET.Tests\bin\Release\token.json\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user,${{ github.workspace }}\GmailAPIHelper.NET.Tests\bin\Release\credentials.json'
        replacements: '__ACCESSTOKEN__=${{ secrets.ACCESS_TOKEN }},__CLIENTID__=${{ secrets.CLIENT_ID }}'
        
    - name: Setup-VSTest
      uses: darenm/Setup-VSTest@v1
      
    - name: Run Tests
      run: vstest.console.exe ${{ github.workspace }}\GmailAPIHelper.NET.Tests\bin\Release\GmailAPIHelper.NET.Tests.dll
  
  DotNetCore_OS-Version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [  ubuntu-latest ]
        dotnet-version: [ '2.1.x' ]
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Dotnet Version (${{ matrix.dotnet-version }})
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Build
      run: dotnet build GmailAPIHelper.CORE.Tests/GmailAPIHelper.CORE.Tests.csproj --configuration Release
      
    - name: Find And Replace Values
      if: ${{ matrix.dotnet-version == '2.1.x' }}
      uses: datamonsters/replace-action@v2
      with:
        files: '${{ github.workspace }}/GmailAPIHelper.CORE.Tests/bin/Release/netcoreapp2.1/token.json/Google.Apis.Auth.OAuth2.Responses.TokenResponse-user'
        replacements: '__ACCESSTOKEN__=${{ secrets.ACCESS_TOKEN }}'
    
    - name: Upload Artifact
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.dotnet-version == '2.1.x' }}
      uses: actions/upload-artifact@v2
      with:
        name: build_files
        path: ${{ github.workspace }}/GmailAPIHelper.CORE.Tests
        retention-days: 90
